### ISSUE TITLE
youtube-search-api 404

### ISSUE THREAD

**Issue by polyma** [hackingbeauty/youtube-autocomplete#1]
I'm getting 
`404  'youtube-search-api' is not in the npm registry.
`

on  install?

**Comment by hackingbeauty** [comment]
Hi, I'm not getting that error.  I just installed react-youtube-autocomplete into a new app, and I do not see that error.  The "youtube-search-api" dependency is definitely available.

Can you run "npm install" inside of your app again?  Perhaps you experienced an intermittent network issue.

Happy to help address any other issues you may find!

**Comment by polyma** [comment]
Still getting the 404. I can't find youtube-search-api on NPM:

https://www.npmjs.com/search?q=youtube-search-api

Could be an error of mine but I've run it on two machines under an older and the latest version of NPM (v3.3.12 and v3.8.7) and still no luck!

**Comment by hackingbeauty** [comment]
Looks like youtube-search-api on npm was removed.  I need to use a different package.  Hold on, will make the swap :)

**Comment by hackingbeauty** [comment]
This issue has been patched.  Can you upgrade to version 1.0.14 of react-youtube-autocomplete and let me know if it works for you?

**Comment by polyma** [comment]
Yup, all good!
