### ISSUE TITLE
importing failed - cannot resolve 

### ISSUE THREAD

**Issue by krishnadubagunta** [hackingbeauty/youtube-autocomplete#6]
`import YoutubeAutocomplete from 'react-youtube-autocomplete';`
and the terminal response is  `Module not found: Can't resolve 'react-youtube-autocomplete' in '/Users/krishna/Desktop/react-tut/src/components'`

and when I see the node_modules folder, react-youtube-autocomplete has no files except package.json and a readme

**Comment by gbenson-wikia** [comment]
Version 1.0.17 is the last one that worked correctly, as near as I can tell.

**Comment by hackingbeauty** [comment]
Hey, sorry for the hassle.  Just patched to version 1.0.20.  Can you try that out and let me know?

**Comment by gbenson-wikia** [comment]
Works great.  Thanks!
